version: "3.8"

# Podman Compose setup for Transmission with wg-netns
# NOTE: This requires the wg-netns namespace to be created FIRST
# Run: sudo wg-netns up transmission-vpn

services:
  transmission:
    image: docker.io/linuxserver/transmission:latest
    container_name: transmission
    # Attach to the wg-netns namespace created on the host
    network_mode: "ns:/run/netns/transmission-vpn"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - transmission-config:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${WATCH_PATH}:/watch
    restart: unless-stopped

volumes:
  transmission-config:
